PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX gn: <http://www.geonames.org/ontology#>

CONSTRUCT
{
    <http://dbpedia.org/ext/gn-alternateName> rdfs:subPropertyOf skos:altLabel .
    ?dbpedia <http://dbpedia.org/ext/gn-alternateName> ?altName .
}

WHERE
{
	?place rdf:type <http://www.geonames.org/ontology#Feature> .
  	?dbpedia owl:sameAs ?place .
  	FILTER ( STRSTARTS(STR(?dbpedia), "http://dbpedia.org/resource/") ) .
    FILTER ( STRSTARTS(STR(?place), "http://sws.geonames.org/") ) .
    ?place gn:alternateName ?altName .
}
